# fly.toml app configuration file generated for backend-red-bush-7768 on 2026-06-24T21:59:55+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-red-bush-7768'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
